name: Deploy to Test Environment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest

    - name: Make deploy script executable
      run: chmod +x deploy_to_test.sh

    - name: Deploy to test environment
      run: ./deploy_to_test.sh

    - name: Debug message
      run: echo "Deploy to Test Environment workflow completed successfully."
